# -*- coding: utf-8 -*-
"""SVM+CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14sC_tOmSm3SpehR-QUlRQe0HydhTXJVH
"""

from google.colab import drive
drive.mount('/content/drive')

import zipfile
import os

# Path to your zip file in Drive
zip_path = '/content/drive/MyDrive/leaf_data_training.zip'

# Unzip to /content/
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/')

# Set the correct base directory (update if needed)
base_dir = "/content/leaf_data_training"

# List classes
print("✅ Dataset directory set to:", base_dir)
print("Subfolders (Classes):", os.listdir(base_dir))

from tensorflow.keras.preprocessing.image import ImageDataGenerator

img_height, img_width = 224, 224
batch_size = 32

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training',
    shuffle=False
)

val_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

class_names = list(train_generator.class_indices.keys())
print("Classes:", class_names)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, GlobalAveragePooling2D, Input

cnn = Sequential([
    Input(shape=(224, 224, 3)),
    Conv2D(32, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(64, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    Conv2D(128, (3, 3), activation='relu'),
    MaxPooling2D(2, 2),
    GlobalAveragePooling2D(),  # replaces Flatten()
])

cnn.summary()

train_features = cnn.predict(train_generator, verbose=1)
val_features = cnn.predict(val_generator, verbose=1)

train_labels = train_generator.classes
val_labels = val_generator.classes

print("Train features shape:", train_features.shape)
print("Train labels shape:", train_labels.shape)

# Step 6: Train SVM Classifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import numpy as np

# Scale features for SVM (important)
scaler = StandardScaler()
train_features_scaled = scaler.fit_transform(train_features)
val_features_scaled = scaler.transform(val_features)

# Train SVM with RBF kernel (you can tune params later)
svm_clf = SVC(kernel='rbf', C=1, gamma='scale', random_state=42)
svm_clf.fit(train_features_scaled, train_labels)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Predict on validation set
val_preds = svm_clf.predict(val_features_scaled)

# Calculate accuracy
val_acc = accuracy_score(val_labels, val_preds)
print(f"Validation Accuracy (SVM on CNN features): {val_acc*100:.2f}%")

# Detailed classification report
print("\nClassification Report:\n", classification_report(val_labels, val_preds, target_names=class_names))

# Confusion matrix plot
cm = confusion_matrix(val_labels, val_preds)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names, cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()

from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Input
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import numpy as np

img_height, img_width = 224, 224
batch_size = 32

# Data generators with MobileNet preprocessing
train_datagen = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    validation_split=0.2
)

train_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='training',
    shuffle=False
)

val_generator = train_datagen.flow_from_directory(
    base_dir,
    target_size=(img_height, img_width),
    batch_size=batch_size,
    class_mode='categorical',
    subset='validation',
    shuffle=False
)

class_names = list(train_generator.class_indices.keys())
print("Classes:", class_names)

# Load MobileNetV2 without top classification layers
base_model = MobileNetV2(input_shape=(img_height, img_width, 3), include_top=False, weights='imagenet')

# Add global average pooling to get feature vector
x = base_model.output
x = GlobalAveragePooling2D()(x)

feature_extractor = Model(inputs=base_model.input, outputs=x)
feature_extractor.summary()

# Extract features
train_features = feature_extractor.predict(train_generator, verbose=1)
val_features = feature_extractor.predict(val_generator, verbose=1)

train_labels = train_generator.classes
val_labels = val_generator.classes

print("Train features shape:", train_features.shape)
print("Validation features shape:", val_features.shape)

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# Scale features
scaler = StandardScaler()
train_features_scaled = scaler.fit_transform(train_features)
val_features_scaled = scaler.transform(val_features)

# Train SVM classifier
svm_clf = SVC(kernel='rbf', C=10, gamma='scale', random_state=42)
svm_clf.fit(train_features_scaled, train_labels)

# Predict on validation set
val_preds = svm_clf.predict(val_features_scaled)

# Calculate accuracy
val_acc = accuracy_score(val_labels, val_preds)
print(f"Validation Accuracy (SVM on MobileNetV2 features): {val_acc*100:.2f}%")

# Classification report
print("\nClassification Report:\n", classification_report(val_labels, val_preds, target_names=class_names))

# Confusion matrix plot
cm = confusion_matrix(val_labels, val_preds)
plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=class_names, yticklabels=class_names, cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')
plt.show()